language: ruby
rvm:
  - 2.3.2

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
