steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    id: Pull Cache
    volumes:
      - name: 'cache'
        path: '/cache'
    entrypoint: bash
    args:
      - -c
      - './bin/build-cache.sh pull && printf "$REVISION_ID" > /workspace/VERSION && touch /cache/warm'

  - name: 'gcr.io/kaniko-project/executor'
    id: Build Container
    secretEnv: [ 'SENTRY_RELEASE_TOKEN' ]
    args:
      - --destination=gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID
      - --cache=true
      - --cache-dir=/kaniko-cache
      - --build-arg=SENTRY_RELEASE_TOKEN
    volumes:
      - name: 'cache'
        path: '/cache'
    waitFor:
      - Pull Cache

  - name: 'gcr.io/kaniko-project/executor'
    id: Build Nginx
    args:
      - --dockerfile=.nginx/Dockerfile
      - --destination=gcr.io/$PROJECT_ID/refsheet-site-nginx:$REVISION_ID
      - --cache=true
      - --cache-dir=/kaniko-cache
      - --build-arg
      - rails_container=localhost
      - --build-arg
      - rails_port=5000
      - --build-arg
      - port=3200
    volumes:
      - name: 'cache'
        path: '/cache'
    waitFor:
      - Pull Cache

  #== Asset Pipeline

  - name: 'gcr.io/cloud-builders/gsutil'
    id: Push Cache
    volumes:
      - name: 'cache'
        path: '/cache'
    entrypoint: bash
    args:
      - -c
      - './bin/build-cache.sh push'
    waitFor:
      - Build Container

  - name: 'gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID'
    id: Report Release
    entrypoint: bash
    dir: /app
    args:
      - -c
      - 'SECRET_KEY_BASE=nothing RDS_DB_ADAPTER=nulldb bundle exec rake refsheet:post_deploy'
    waitFor:
      - Build Container

  #== DEPLOY

  # Deploy Web
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy Staging
    args: ['set', 'image', 'deployment', 'refsheet-prod-staging', "refsheet-prod-staging=gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID"]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=refsheet-prod-clone-1'
    waitFor:
      - Build Container

  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy Nginx
    args: ['set', 'image', 'deployment', 'refsheet-prod-staging', "refsheet-prod-staging-nginx=gcr.io/$PROJECT_ID/refsheet-site-nginx:$REVISION_ID"]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=refsheet-prod-clone-1'
    waitFor:
      - Build Nginx
options:
  machineType: 'N1_HIGHCPU_8'

secrets:
  - kmsKeyName: projects/refsheet-239409/locations/global/keyRings/refsheet-ci/cryptoKeys/refsheet-ci
    secretEnv:
      SENTRY_RELEASE_TOKEN: CiQA5Rk5Qwhkg8NawPC6YDtmJXE/nHXyvDPR4eVUeCCLkuEbwv8SaQBhT4yKyIFU3xeUXa7oXdn5aYURow/xYjr9Ksr5GfPiduSy5/iJEHVY4jlzOrr3xxhb/qEfNu9P2EstXsKg/BnpBlZJ4gtkB4VM5IebjWmy8JTjT03BgfB2gpDbDZseKEZZk8m2nKYiCw==

timeout: 3600s
