steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    id: Pull Cache
    volumes:
      - name: 'cache'
        path: '/cache'
    entrypoint: bash
    args:
      - -c
      - './bin/build-cache.sh pull && printf "$REVISION_ID" > /workspace/VERSION && touch /cache/warm'

  - name: 'gcr.io/kaniko-project/executor'
    id: Build Container
    secretEnv: ['SENTRY_RELEASE_TOKEN']
    args:
      - --destination=gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID
      - --cache=true
      - --cache-dir=/kaniko-cache
      - --build-arg=SENTRY_RELEASE_TOKEN
    volumes:
      - name: 'cache'
        path: '/cache'
      - name: 'artifacts'
        path: '/artifacts'
    waitFor:
      - Pull Cache

  - name: 'gcr.io/cloud-builders/gsutil'
    id: Upload Artifacts
    volumes:
      - name: 'artifacts'
        path: '/artifacts'
    args:
      - -m
      - -h
      - 'Cache-Control:"Cache-Control: public, max-age=31559652"'
      - cp
      - -a
      - public-read
      - -rZ
      - /artifacts/*
      - gs://assets.refsheet.net/
    waitFor:
      - Build Container

  - name: 'gcr.io/cloud-builders/gsutil'
    id: Push Cache
    volumes:
      - name: 'cache'
        path: '/cache'
    entrypoint: bash
    args:
      - -c
      - './bin/build-cache.sh push'
    waitFor:
      - Build Container

  - name: 'gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID'
    id: Report Release
    entrypoint: bash
    dir: /app
    args:
      - -c
      - 'SECRET_KEY_BASE=nothing RDS_DB_ADAPTER=nulldb bundle exec rake refsheet:post_deploy'
    waitFor:
      - Build Container

  #== DEPLOY

  # Deploy Web
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy Web
    args: ['set', 'image', 'deployment', 'refsheet-prod', "refsheet-prod=gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID"]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=refsheet-prod-clone-1'
    waitFor:
      - Upload Artifacts

  # Deploy Worker
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy Worker
    args: ['set', 'image', 'deployment', 'refsheet-prod-worker', "refsheet-prod-worker=gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID"]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=refsheet-prod-clone-1'
    waitFor:
      - Upload Artifacts

# Create Secrets with:
# printf "value" | gcloud kms encrypt --plaintext-file=- --ciphertext-file=- --location=global --keyring=refsheet-ci \
#   --key=refsheet-ci | base64 -w0

secrets:
  - kmsKeyName: projects/refsheet-239409/locations/global/keyRings/refsheet-ci/cryptoKeys/refsheet-ci
    secretEnv:
      SENTRY_RELEASE_TOKEN: CiQA5Rk5Qwhkg8NawPC6YDtmJXE/nHXyvDPR4eVUeCCLkuEbwv8SaQBhT4yKyIFU3xeUXa7oXdn5aYURow/xYjr9Ksr5GfPiduSy5/iJEHVY4jlzOrr3xxhb/qEfNu9P2EstXsKg/BnpBlZJ4gtkB4VM5IebjWmy8JTjT03BgfB2gpDbDZseKEZZk8m2nKYiCw==

timeout: 3600s
