steps:
  - name: 'gcr.io/kaniko-project/executor'
    args:
    - --destination=gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID
    - --cache=true

  #== TEST

#  - name: 'gcr.io/$PROJECT_ID/refsheet-site-ci'
#    args: ['rspec']

#  - name: 'gcr.io/$PROJECT_ID/refsheet-site-ci'
#    args: ['yaml-lint', '.kubernetes/*.{yml,yaml}']

  #== Asset Pipeline
#  - name: 'gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID'
#    args: ['']

  #== DEPLOY

  # Deploy Web
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment', 'refsheet-prod', "refsheet-prod=gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID"]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=refsheet-prod-clone-1'

  # Deploy Worker
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment', 'refsheet-prod-worker', "refsheet-prod-worker=gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID"]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=refsheet-prod-clone-1'

artifacts:
  objects:
    location: "gs://refsheet-prod-assets/"
    paths:
      - "public/*"
      - "public/assets/*"

timeout: 3600s