steps:
  - name: 'gcr.io/kaniko-project/executor'
    args:
      - --destination=gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID
      - --cache=true

  #== TEST

  #  - name: 'gcr.io/$PROJECT_ID/refsheet-site-ci'
  #    args: ['rspec']

  #  - name: 'gcr.io/$PROJECT_ID/refsheet-site-ci'
  #    args: ['yaml-lint', '.kubernetes/*.{yml,yaml}']

  #== Asset Pipeline
  - name: 'gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID'
    volumes:
      - name: 'artifacts'
        path: '/artifacts'
    entrypoint: 'bash'
    args:
      - -c
      - 'cp -R /app/public/* /artifacts'

  - name: 'gcr.io/cloud-builders/gsutil'
    volumes:
      - name: 'artifacts'
        path: '/artifacts'
    args:
      - -m
      - cp
      - -r
      - /artifacts/*
      - gs://assets.refsheet.net/

  #== DEPLOY

  # Deploy Web
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment', 'refsheet-prod-staging', "refsheet-prod-staging=gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID"]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=refsheet-prod-clone-1'

timeout: 3600s