steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    id: Pull Cache
    volumes:
      - name: 'cache'
        path: '/cache'
    entrypoint: bash
    args:
      - -c
      - './bin/build-cache.sh pull'

  - name: 'gcr.io/kaniko-project/executor'
    id: Build Container
    args:
      - --destination=gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID
      - --build-arg=VERSION=$REVISION_ID
      - --cache=true
    volumes:
      - name: 'cache'
        path: '/cache'
      - name: 'artifacts'
        path: '/artifacts'
    waitFor:
      - Pull Cache

  #== Asset Pipeline
#  - name: 'gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID'
#    id: Extract Artifacts
#    volumes:
#      - name: 'artifacts'
#        path: '/artifacts'
#    entrypoint: 'bash'
#    args:
#      - -c
#      - 'cp -R /app/public/* /artifacts'
#    waitFor:
#      - Build Container

  - name: 'gcr.io/cloud-builders/gsutil'
    id: Upload Artifacts
    volumes:
      - name: 'artifacts'
        path: '/artifacts'
    args:
      - -m
      - -h
      - 'Cache-Control:"Cache-Control: public, max-age=31559652"'
      - cp
      - -a
      - public-read
      - -rnZ
      - /artifacts/*
      - gs://assets.refsheet.net/
    waitFor:
      - Build Container

  - name: 'gcr.io/cloud-builders/gsutil'
    id: Push Cache
    volumes:
      - name: 'cache'
        path: '/cache'
    entrypoint: bash
    args:
      - -c
      - './bin/build-cache.sh push'
    waitFor:
      - Build Container

  #== DEPLOY

  # Deploy Web
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy Staging
    args: ['set', 'image', 'deployment', 'refsheet-prod-staging', "refsheet-prod-staging=gcr.io/$PROJECT_ID/refsheet-site:$REVISION_ID"]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=refsheet-prod-clone-1'
    waitFor:
      - Upload Artifacts

timeout: 3600s