version: '2.3'

services:
  postgres:
    image: 'littlebobbytables/postgres-pg_similarity'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass refsheet
    volumes:
      - 'redis:/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
      - 'bundle:/usr/local/bundle'
    env_file:
      - '.env'
    environment:
      FORMATION: web=1 webpacker=1

  worker:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - 'bundle:/usr/local/bundle'
    env_file:
      - '.env'
    environment:
      FORMATION: worker=1

#  cable:
#    depends_on:
#      - 'redis'
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    ports:
#      - '28080:28080'
#    volumes:
#      - '.:/app'
#    env_file:
#      - '.env'
#    environment:
#      FORMATION: cable=1

volumes:
  redis:
  postgres:
  bundle: