version: '2'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass refsheet
    volumes:
      - 'redis:/data'

  web:
    depends_on:
      - postgres
      - redis
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/bundle
      - node_modules:/node_modules
    env_file:
      - .env
    command: rails server -p 3000 -b '0.0.0.0'

#  worker:
#    depends_on:
#      - 'postgres'
#      - 'redis'
#      - 'cache'
#    build: .
#    command: rake resque:work QUEUE=*
#    volumes:
#      - '.:/app'
#      - bundle:/bundle
#    env_file:
#      - '.env'

volumes:
  redis:
  bundle:
  node_modules:
  postgres:
