apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: image-redrive
spec:
  schedule: '*/15 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: refsheet-prod
            tier: refsheet-prod-job
          annotations:
            configHash: 8f79dd457c6080a6373077ca6c3152a94b28b86e118014e0f0fc01fc4f9df144
        spec:
          restartPolicy: Never
          containers:
          - name: image-redrive
            image: gcr.io/refsheet-239409/refsheet-site:a3e9aa9b4d0eef0e1bf7ce182365309b4a9adf17
            imagePullPolicy: Always
            command:
            - bundle
            args:
            - exec
            - rails
            - runner
            - ImageRedriveJob.perform_now
            envFrom:
            - configMapRef:
                name: refsheet-prod
            - secretRef:
                name: refsheet-prod-secret
