apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: image-redrive
spec:
  schedule: '*/15 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: refsheet-prod
            tier: refsheet-prod-job
          annotations:
            configHash: 17459fa03f3be4a3c13bb5f568c7851b0ae4360da9aff7d75221a668cb7e2917
        spec:
          restartPolicy: Never
          containers:
          - name: image-redrive
            image: gcr.io/refsheet-239409/refsheet-site:6ca1748bd25a19d7961e65b16791cb3def114719
            imagePullPolicy: Always
            command:
            - bundle
            args:
            - exec
            - rails
            - runner
            - ImageRedriveJob.perform_now
            envFrom:
            - configMapRef:
                name: refsheet-prod
            - secretRef:
                name: refsheet-prod-secret
