apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: image-redrive
spec:
  schedule: '*/15 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: refsheet-prod
            tier: refsheet-prod-job
          annotations:
            configHash: c3e3d1e79aed5fc0e4bd6b9a9f1772d195a25b9445ce41844420ba990a815573
        spec:
          restartPolicy: Never
          containers:
          - name: image-redrive
            image: gcr.io/refsheet-239409/refsheet-site:f8b89f41acf02f293724a27ad69a12ab7c421b3a
            imagePullPolicy: Always
            command:
            - bundle
            args:
            - exec
            - rails
            - runner
            - ImageRedriveJob.perform_now
            envFrom:
            - configMapRef:
                name: refsheet-prod
            - secretRef:
                name: refsheet-prod-secret
