apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: image-redrive
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: refsheet-prod
            tier: refsheet-prod-job
          annotations:
            configHash: 865d934592b343dc93d6e8e43c4b6adaa208d30a0b8b7cfe0381c157d5598e38
        spec:
          restartPolicy: Never
          containers:
          - name: image-redrive
            image: gcr.io/refsheet-239409/refsheet-site:b084e85471a41b80c5f12a5a7a968781fc7f5ffa
            imagePullPolicy: Always
            command:
            - bundle
            args:
            - exec
            - rails
            - runner
            - ImageRedriveJob.perform_now
            envFrom:
            - configMapRef:
                name: refsheet-prod
            - secretRef:
                name: refsheet-prod-secret
