apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: image-redrive
spec:
  schedule: '*/15 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: refsheet-prod
            tier: refsheet-prod-job
          annotations:
            configHash: 8e0fcc024baaaaefc2835effee4f1095ae25bf68e47755129ea2b9d4010217b1
        spec:
          restartPolicy: Never
          containers:
          - name: image-redrive
            image: gcr.io/refsheet-239409/refsheet-site:5fbd9fc90748a6388f72aebdd8d0245be33a4f35
            imagePullPolicy: Always
            command:
            - bundle
            args:
            - exec
            - rails
            - runner
            - ImageRedriveJob.perform_now
            envFrom:
            - configMapRef:
                name: refsheet-prod
            - secretRef:
                name: refsheet-prod-secret
