branch-defaults:
  image-management:
    environment: refsheet-staging
  master:
    environment: refsheet-staging
  production:
    environment: refsheet-prod
environment-defaults:
  refsheet-staging:
    branch: null
    repository: null
global:
  application_name: refsheet
  branch: null
  default_ec2_keyname: kenku-dev-1
  default_platform: Ruby 2.3 (Puma)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
