production: &default
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  s3_region: <%= ENV['S3_REGION'] || "us-east-1" %>

development:
  <<: *default
  bucket: refsheet-dev

test:
  <<: *default
  bucket: refsheet-test
