development:
  adapter: postgresql

test:
  adapter: async

production:
  adapter: redis
  url: redis://refsheet-prod-redis.g5lbhu.0001.use1.cache.amazonaws.com:6379
  channel_prefix: refsheet_prod_cable
