default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  password: <%= ENV['DB_PASSWORD'] || 'fishsticks' %>
  database: <%= ENV['DB_DATABASE'] || 'refsheet-site' %>
  username: <%= ENV['DB_USERNAME'] || 'refsheet' %>
  timeout: 5000
  pool: <%= ENV['DB_POOL'] || 10 %>
  port: <%= ENV['DB_PORT'] || 5432 %>


development:
  <<: *default

test:
  <<: *default
  database: refsheet-site-test

production:
  adapter: <%= ENV['RDS_DB_ADAPTER'] || 'postgresql' %>
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 10 %>
  timeout: 5000
