default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  password: <%= ENV['DB_PASSWORD'] || 'fishsticks' %>
  database: <%= ENV['DB_DATABASE'] || 'refsheet-site' %>
  username: <%= ENV['DB_USERNAME'] || 'refsheet' %>
  timeout: 5000
  pool: <%= ENV['DB_POOL'] || 10 %>
  port: <%= ENV['DB_PORT'] || 5432 %>


development:
  <<: *default
  username: <%= ENV['DB_USERNAME'] || 'refsheet-site-dev' %>
  database: <%= ENV['DB_DATABASE'] || 'refsheet-site-dev' %>

test:
  <<: *default
  username: <%= ENV['DB_USERNAME'] || 'refsheet-site-test' %>
  database: <%= ENV['DB_DATABASE'] || 'refsheet-site-test' %>

production:
  adapter: postgresql
  database: <%= ENV['DB_DATABASE'] || ENV['RDS_DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] || ENV['RDS_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] || ENV['RDS_PASSWORD'] %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 10 %>
  timeout: 5000
<% if ENV['CLOUD_SQL_CONNECTION_NAME'] %>
  host: /cloudsql/<%= ENV['CLOUD_SQL_CONNECTION_NAME'] %>
<% else %>
  host: <%= ENV['DB_HOST'] || ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] || ENV['RDS_PORT'] || 5432 %>
<% end %>