apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: refsheet-prod
  labels:
    app: refsheet-prod
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: refsheet-prod
        tier: frontend
        run: refsheet-prod
      annotations:
        configHash: 8f79dd457c6080a6373077ca6c3152a94b28b86e118014e0f0fc01fc4f9df144
    spec:
      containers:
      - name: refsheet-prod
        image: gcr.io/refsheet-239409/refsheet-site:3fd50029541f8ecc2abb5421511d39a04810fe84
        imagePullPolicy: Always
        livenessProbe:
          timeoutSeconds: 60
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        readinessProbe:
          timeoutSeconds: 60
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        command:
        - bundle
        args:
        - exec
        - rails
        - server
        - -b
        - 0.0.0.0
        - -p
        - "3000"
        envFrom:
        - configMapRef:
            name: refsheet-prod
        - secretRef:
            name: refsheet-prod-secret
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: "0.25"
            memory: 500M
          limits:
            cpu: "0.6"
            memory: 1G
