apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: refsheet-prod
  labels:
    app: refsheet-prod
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: refsheet-prod
        tier: frontend
      annotations:
        configHash: 4238c08a8ce1b6ee9b74cf744c89f20d693fe4002ae51d694366fe7f12da57e4
    spec:
      containers:
      - name: refsheet-prod
        image: gcr.io/refsheet-239409/refsheet-site:eb19ddbf576d055b5564d8589b3696025b191bd0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        command:
        - bundle
        args:
        - exec
        - rails
        - server
        - -b
        - 0.0.0.0
        - -p
        - "3000"
        envFrom:
        - configMapRef:
            name: refsheet-prod
        - secretRef:
            name: refsheet-prod-secret
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 500M
          limits:
            cpu: "1"
            memory: 1G
