apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: refsheet-prod-worker
  labels:
    app: refsheet-prod
    tier: worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: refsheet-prod
        tier: refsheet-prod-worker
      annotations:
        configHash: bd22984fa141790ebdb3b8713044d21fa30b181108cc590139cef1565cb42a7c
    spec:
      containers:
      - name: refsheet-prod-worker
        image: gcr.io/refsheet-239409/refsheet-site:55c735e7e98b211f58e24c40e792c6f1fbb26318
        imagePullPolicy: Always
        command:
        - bundle
        args:
        - exec
        - rake
        - resque:work
        - QUEUE=priority,refsheet_image_processing,refsheet_application_queue
        envFrom:
        - configMapRef:
            name: refsheet-prod
        - secretRef:
            name: refsheet-prod-secret
        resources:
          requests:
            cpu: "0.5"
            memory: 1G
          limits:
            cpu: "1"
            memory: 2G
