apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: refsheet-prod
  labels:
    app: refsheet-prod
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: refsheet-prod
        tier: frontend
        run: refsheet-prod
      annotations:
        configHash: 19006b11742c746f2ada42c9bf929a340681cbc403ce8da53ab3ea276d0610b2
    spec:
      containers:
      - name: refsheet-prod
        image: gcr.io/refsheet-239409/refsheet-site:5b991029b01a74a2c5cd1485903c4a2ec6c65fd4
        imagePullPolicy: Always
        livenessProbe:
          timeoutSeconds: 30
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        readinessProbe:
          timeoutSeconds: 30
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        command:
        - bundle
        args:
        - exec
        - rails
        - server
        - -b
        - 0.0.0.0
        - -p
        - "3000"
        envFrom:
        - configMapRef:
            name: refsheet-prod
        - secretRef:
            name: refsheet-prod-secret
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: "0.15"
            memory: 500M
          limits:
            cpu: "0.6"
            memory: 1G
