apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: refsheet-prod
  labels:
    app: refsheet-prod
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: refsheet-prod
        tier: frontend
      annotations:
        configHash: 17459fa03f3be4a3c13bb5f568c7851b0ae4360da9aff7d75221a668cb7e2917
    spec:
      containers:
      - name: refsheet-prod
        image: gcr.io/refsheet-239409/refsheet-site:6ca1748bd25a19d7961e65b16791cb3def114719
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        command:
        - bundle
        args:
        - exec
        - rails
        - server
        - -b
        - 0.0.0.0
        - -p
        - "3000"
        envFrom:
        - configMapRef:
            name: refsheet-prod
        - secretRef:
            name: refsheet-prod-secret
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: "0.15"
            memory: 500M
          limits:
            cpu: "0.3"
            memory: 1G
