apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: refsheet-prod-worker
  labels:
    app: refsheet-prod
    tier: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: refsheet-prod
        tier: refsheet-prod-worker
      annotations:
        configHash: 1da0271815dc950744f8bcf5835f02e23c1437ec3f29491a9c731d03d300a9b1
    spec:
      containers:
      - name: refsheet-prod-worker
        image: gcr.io/refsheet-239409/refsheet-site:7730d5a889434af630fe45cc16f4d32a8db954a2
        imagePullPolicy: Always
        command:
        - bundle
        args:
        - exec
        - rake
        - resque:work
        - QUEUE=*
        envFrom:
        - configMapRef:
            name: refsheet-prod
        - secretRef:
            name: refsheet-prod-secret
        resources:
          requests:
            cpu: "0.5"
            memory: 1G
          limits:
            cpu: "1"
            memory: 2G
