apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: refsheet-prod
  labels:
    app: refsheet-prod
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: refsheet-prod
        tier: frontend
      annotations:
        configHash: 865d934592b343dc93d6e8e43c4b6adaa208d30a0b8b7cfe0381c157d5598e38
    spec:
      containers:
      - name: refsheet-prod
        image: gcr.io/refsheet-239409/refsheet-site:b084e85471a41b80c5f12a5a7a968781fc7f5ffa
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        command:
        - bundle
        args:
        - exec
        - rails
        - server
        - -b
        - 0.0.0.0
        - -p
        - "3000"
        envFrom:
        - configMapRef:
            name: refsheet-prod
        - secretRef:
            name: refsheet-prod-secret
        ports:
        - containerPort: 3000
          protocol: TCP
