apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: refsheet-prod
  labels:
    app: refsheet-prod
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: refsheet-prod
        tier: frontend
        run: refsheet-prod
      annotations:
        configHash: 34f6260336c8c7f690cae53f740197ed6f11e52aac74f114cee0bfd6f924ad4f
    spec:
      containers:
      - name: refsheet-prod
        image: gcr.io/refsheet-239409/refsheet-site:de15dc1cb9e88203521c688d9019f7aba86fed16
        imagePullPolicy: Always
        livenessProbe:
          timeoutSeconds: 1200
          initialDelaySeconds: 120
          periodSeconds: 2000
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        readinessProbe:
          timeoutSeconds: 1200
          initialDelaySeconds: 120
          periodSeconds: 2000
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        command:
        - bundle
        args:
        - exec
        - rails
        - server
        - -b
        - 0.0.0.0
        - -p
        - "3000"
        envFrom:
        - configMapRef:
            name: refsheet-prod
        - secretRef:
            name: refsheet-prod-secret
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: "0.25"
            memory: 500M
          limits:
            cpu: "0.6"
            memory: 1G
