apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: refsheet-prod-staging
  labels:
    app: refsheet-prod-staging
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: refsheet-prod-staging
        tier: frontend
        run: refsheet-prod-staging
      annotations:
        configHash: b6434529026540e58e2751ed60fcfe48ccee9201aa8a9294c7742e58b3a3d66c
    spec:
      volumes:
      - name: refsheet-prod-storage
        secret:
          secretName: refsheet-prod-storage
      containers:
      - name: refsheet-prod-staging-nginx
        image: gcr.io/refsheet-239409/refsheet-site-nginx:bb7c0063121bce5885632829fdc77dbd67ea15c8
        imagePullPolicy: Always
        livenessProbe:
          periodSeconds: 120
          timeoutSeconds: 120
          httpGet:
            path: /nhealth
            port: 3200
            scheme: HTTP
        readinessProbe:
          periodSeconds: 120
          timeoutSeconds: 120
          httpGet:
            path: /nhealth
            port: 3200
            scheme: HTTP
        ports:
          - containerPort: 3000
            protocol: TCP
        resources:
          requests:
            cpu: "0.1"
            memory: 64M
          limits:
            cpu: "0.6"
            memory: 256M
      - name: refsheet-prod-staging
        image: gcr.io/refsheet-239409/refsheet-site:ec0878bc35398957ef78c8bfe77c4fe3b1a71812
        imagePullPolicy: Always
        livenessProbe:
          periodSeconds: 120
          timeoutSeconds: 120
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        readinessProbe:
          periodSeconds: 120
          timeoutSeconds: 120
          httpGet:
            path: /health.json
            port: 3000
            scheme: HTTP
        command:
        - bundle
        args:
        - exec
        - rails
        - server
        - -b
        - 0.0.0.0
        - -p
        - "3000"
        env:
        - name: DEFAULT_URL_HOST
          value: kube.refsheet.net
        - name: RAILS_MAX_THREADS
          value: "15"
        - name: WEB_CONCURRENCY
          value: "2"
        envFrom:
        - configMapRef:
            name: refsheet-prod
        - secretRef:
            name: refsheet-prod-secret
        volumeMounts:
        - name: refsheet-prod-storage
          mountPath: /secrets/storage
          readOnly: true
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: "0.5"
            memory: 500M
          limits:
            cpu: "1"
            memory: 1G
