apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: refsheet-prod-worker
  labels:
    app: refsheet-prod
    tier: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: refsheet-prod
        tier: refsheet-prod-worker
      annotations:
        configHash: 865d934592b343dc93d6e8e43c4b6adaa208d30a0b8b7cfe0381c157d5598e38
    spec:
      containers:
      - name: refsheet-prod-worker
        image: gcr.io/refsheet-239409/refsheet-site:6aaa02ef4565fa23d676f2b20872dae00aa71318
        imagePullPolicy: Always
        command:
        - bundle
        args:
        - exec
        - rake
        - resque:work
        - QUEUE=*
        envFrom:
        - configMapRef:
            name: refsheet-prod
        - secretRef:
            name: refsheet-prod-secret
